# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{couch_tomato}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Plastic Trophy"]
  s.date = %q{2009-10-18}
  s.description = %q{Ruby persistence layer for CouchDB, inspired by and forked from Couch Potato}
  s.email = %q{dev@plastictrophy.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE.txt",
     "README.md",
     "init.rb",
     "lib/core_ext/date.rb",
     "lib/core_ext/duplicable.rb",
     "lib/core_ext/extract_options.rb",
     "lib/core_ext/inheritable_attributes.rb",
     "lib/core_ext/object.rb",
     "lib/core_ext/string.rb",
     "lib/core_ext/symbol.rb",
     "lib/core_ext/time.rb",
     "lib/couch_tomato.rb",
     "lib/couch_tomato/database.rb",
     "lib/couch_tomato/js_view_source.rb",
     "lib/couch_tomato/migration.rb",
     "lib/couch_tomato/migrator.rb",
     "lib/couch_tomato/persistence.rb",
     "lib/couch_tomato/persistence/base.rb",
     "lib/couch_tomato/persistence/belongs_to_property.rb",
     "lib/couch_tomato/persistence/callbacks.rb",
     "lib/couch_tomato/persistence/dirty_attributes.rb",
     "lib/couch_tomato/persistence/json.rb",
     "lib/couch_tomato/persistence/magic_timestamps.rb",
     "lib/couch_tomato/persistence/properties.rb",
     "lib/couch_tomato/persistence/simple_property.rb",
     "lib/couch_tomato/persistence/validation.rb",
     "lib/couch_tomato/replicator.rb",
     "lib/tasks/couch_tomato.rake",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/plastictrophy/couch_tomato}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby persistence layer for CouchDB, inspired by and forked from Couch Potato}
  s.test_files = [
    "spec/callbacks_spec.rb",
     "spec/comment.rb",
     "spec/create_spec.rb",
     "spec/custom_view_spec.rb",
     "spec/destroy_spec.rb",
     "spec/fixtures/address.rb",
     "spec/fixtures/person.rb",
     "spec/property_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/attributes_spec.rb",
     "spec/unit/callbacks_spec.rb",
     "spec/unit/create_spec.rb",
     "spec/unit/customs_views_spec.rb",
     "spec/unit/database_spec.rb",
     "spec/unit/dirty_attributes_spec.rb",
     "spec/unit/string_spec.rb",
     "spec/unit/view_query_spec.rb",
     "spec/update_spec.rb",
     "test/test_helper.rb",
     "test/unit/database_test.rb",
     "test/unit/js_view_test.rb",
     "test/unit/property_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<validatable>, [">= 0"])
      s.add_runtime_dependency(%q<couchrest>, [">= 0.24"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<validatable>, [">= 0"])
      s.add_dependency(%q<couchrest>, [">= 0.24"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<validatable>, [">= 0"])
    s.add_dependency(%q<couchrest>, [">= 0.24"])
  end
end
